name: Issue Movement Automation

on:
  issues:
    types:
      - opened
      - edited
      - labeled
      - closed

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issues to appropriate columns
        uses: actions/github-script@v4
        with:
          script: |
            const project_id = PVT_kwHOCbSMgM4A3VVM;  
            const todo_column_id = 47fc9ee4;  
            const in_progress_column_id = df73e18b;  
            const done_column_id = 98236657;  

            // Move to "Done" column when the issue is closed
            if (github.context.payload.issue.state === 'closed') {
              await github.projects.moveCard({
                project_id: project_id,
                column_id: done_column_id,
                card_id: github.context.payload.issue.id
              });
            } else if (github.context.payload.issue.state === 'open') {
              // Move to "In Progress" if the issue has "in-progress" label
              if (github.context.payload.issue.labels.some(label => label.name === 'in-progress')) {
                await github.projects.moveCard({
                  project_id: project_id,
                  column_id: in_progress_column_id,
                  card_id: github.context.payload.issue.id
                });
              } else {
                // Default to "To Do" if no "in-progress" label
                await github.projects.moveCard({
                  project_id: project_id,
                  column_id: todo_column_id,
                  card_id: github.context.payload.issue.id
                });
              }
            }
